config/routes.rb
Rhino::Application.routes.draw do
  get "s/:id" => "songs#proxy", as: :song_proxy
  resources :songs

  root 'songs#index'

end

app/models/song.rb
class Song < ActiveRecord::Base
  validates_presence_of :title, :filepicker_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy, :proxy]

  def proxy
    @song.plays += 1
    @song.save
    redirect_to @song.filepicker_url
  end

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to songs_path, notice: 'Song was successfully created.' }
        format.json { render action: 'show', status: :created, location: @song }
      else
        format.html { render action: 'new' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to songs_path, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:filepicker_url, :title, :plays, :length)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_element form, name, element, label_name=nil, opts={}
    label_name ||= name.to_s.humanize
    if opts.class == Hash
      if opts[:class]
        unless opts[:class].include? "input-"
          opts[:class] += " input-xxlarge"
        end
      else
        opts[:class] = "input-xxlarge"
      end
      if element == :text_area
        if !opts[:rows]
          opts.merge!(rows: 10)
        end
      end
    end
    html = '<div class="field control-group">'
    if form.nil?
      html << send(:label, name, label_name, class: 'control-label')
    else
      html << form.send(:label, name, label_name, class: 'control-label')
    end
    html << '<div class="controls">'
    if form.nil?
      html << send(element.to_s+"_tag", name, nil, opts)
    else
      html << form.send(element, name, opts)
    end
    html << '</div></div>'
    html.html_safe
  end

  def proxy_path(song)
    song_proxy_url(id: song.id)
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Rhino"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Rhinosaurus

    .container

      .row
        .span12
          = bootstrap_flash
          = yield
        /.span3
        /  .well.sidebar-nav
        /    %h3 Sidebar
        /    %ul.nav.nav-list
        /      %li.nav-header Sidebar
        /      %li= link_to "Link 1", "/path1"
        /      %li= link_to "Link 2", "/path2"
        /      %li= link_to "Link 3", "/path3"

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = filepicker_js_include_tag
    = yield :javascript

app/views/songs/_form.html.haml
= form_for @song, :html => { :class => 'form-horizontal' } do |f|
  = form_element f, :title, :text_field
  .field.control-group
    / # = f.label :filepicker_url, "Upload a Song"
    .controls
      = f.filepicker_field :filepicker_url, button_class: 'btn', onchange: 'pickAvatar(event)', mimetypes: 'audio/*', button_text: "Choose Song"
      %p.file-success
      = f.hidden_field :filepicker_url
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), songs_path, :class => 'btn'

app/views/songs/edit.html.haml
- model_class = Song
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/songs/index.html.haml
- model_class = Song
.page-header
  %h3=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped.table-bordered.song-table
  %thead
    %tr
      %th Title
      %th
      %th Play Count
      %th
  %tbody
    - if @songs.empty?
      %tr
        %td{colspan: 4}
          %em No songs to show...
    - @songs.each do |song|
      %tr
        %td= song.title
        %td= content_tag :audio, "", src: proxy_path(song), controls: true, preload: :none
        %td= song.plays
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_song_path(song), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), song_path(song), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to "Add a Song", new_song_path, :class => 'btn btn-primary'

- content_for :javascript do
  / :javascript
  /   $(function() {
  /     // Blog is the app name
  /     window.router = new Rhino.Routers.SongsRouter({songs: #{@songs.to_json.html_safe}});
  /     Backbone.history.start();
  /   });

app/views/songs/new.html.haml
- model_class = Song
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/songs/show.html.haml
- model_class = Song
.page-header
  %h1=



.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), songs_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_song_path(@song), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), song_path(@song), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'